'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class UtilityEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=UtilityEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblUtility_Access() As DbSet(Of tblUtility_Access)

    Public Overridable Function spUtility_GetLDAPGroupsForPage(pageName As String) As ObjectResult(Of Nullable(Of Integer))
        Dim pageNameParameter As ObjectParameter = If(pageName IsNot Nothing, New ObjectParameter("PageName", pageName), New ObjectParameter("PageName", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spUtility_GetLDAPGroupsForPage", pageNameParameter)
    End Function

    Public Overridable Function spUtility_GetLDAPIsAuthorized(ldapUsername As String, pageName As String) As ObjectResult(Of String)
        Dim ldapUsernameParameter As ObjectParameter = If(ldapUsername IsNot Nothing, New ObjectParameter("LdapUsername", ldapUsername), New ObjectParameter("LdapUsername", GetType(String)))

        Dim pageNameParameter As ObjectParameter = If(pageName IsNot Nothing, New ObjectParameter("PageName", pageName), New ObjectParameter("PageName", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("spUtility_GetLDAPIsAuthorized", ldapUsernameParameter, pageNameParameter)
    End Function

    Public Overridable Function spUtility_GetLDAPUserGroups(ldapUsername As String) As Integer
        Dim ldapUsernameParameter As ObjectParameter = If(ldapUsername IsNot Nothing, New ObjectParameter("LdapUsername", ldapUsername), New ObjectParameter("LdapUsername", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("spUtility_GetLDAPUserGroups", ldapUsernameParameter)
    End Function

    Public Overridable Function spUtility_GetPageURL(pageName As String) As ObjectResult(Of String)
        Dim pageNameParameter As ObjectParameter = If(pageName IsNot Nothing, New ObjectParameter("PageName", pageName), New ObjectParameter("PageName", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("spUtility_GetPageURL", pageNameParameter)
    End Function

End Class
